<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [8]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
print(greeting("Super Man"))

print(greeting(name="Super Man"))

greet=greeting(name='Super Man')
print(greet)

print(greeting(name='Super Man'))

def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

Hello Super Man!
Hello Super Man!
Hello Super Man!
Hello Super Man!


### 1.2 Named functions that don’t return

eg. print() which does not return a value but we require it to to save date.


### 1.3 Anonymous functions

In [14]:
my_short_function = lambda name: f"Hello {name}!"


my_short_function(name="Super Man")

numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

print(sorted(numbers))                        # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

print(sorted(numbers, key=lambda x: x[1]))     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[0, 9, 19], [1, 8, 18], [2, 7, 17], [3, 6, 16], [4, 5, 15], [5, 4, 14], [6, 3, 13], [7, 2, 12], [8, 1, 11], [9, 0, 10]]
[[9, 0, 10], [8, 1, 11], [7, 2, 12], [6, 3, 13], [5, 4, 14], [4, 5, 15], [3, 6, 16], [2, 7, 17], [1, 8, 18], [0, 9, 19]]


### 1.4 Optional arguments

In [18]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

print(greeting())

print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

Hello no one!
I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

Abstraction is to break up complicated solutions into modular chunks to make it easier to deal with as yuo do not need to deal with all the information at once.

### 2.2 A word of caution

Do not have too many arguments as it will be difficult to read your code and it also increases computational overheads.

## Exercise 1 :  Do you know why?

'Return' is within the 'if' statement, thus, it acts as the alternate 'else' statemnt.

## Exercise 2 :  Calculator functions

In [35]:
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

def add(var1, var2):
    return var1+var2
print(add(x, y))

def subtract(var1, var2):
    return var1-var2
print(subtract(x, y))

def multiply(var1, var2):
    return var1*var2
print(multiply(x, y))

def divide(var1, var2):
    for i in y:
        if i==0:
            return f"undefined"
    return var1/var2
print(divide(x, y))

[100 100 100 100 100]
[-28 -32 -12  52 -46]
[2304 2244 2464 1824 1971]
[0.5625     0.51515152 0.78571429 3.16666667 0.36986301]


## Exercise 3 :  max_info() with NumPy

In [ ]:



# Your solution here


