<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [30]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

### 1.2 Subsetting by masking (Arrays only)

In [2]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

print(np_array[my_mask])

print(np_array[np_array > 3])

print(np_array[~(np_array > 3)])                       # '~' means 'NOT'

print(np_array[(np_array > 3) & (np_array < 8)])         # '&' means 'AND'

print(np_array[(np_array < 3) | (np_array > 8)])         # '|' means 'OR'

[False False False  True  True  True  True  True  True  True]
[ 4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]
[1 2 3]
[4 5 6 7]
[ 1  2  9 10]


### 1.3 Indexing & Slicing 2D Lists

In [4]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

print(py_list_2d[3])        # What is at position 4 (index 3)?

print(py_list_2d[3][0])     # FIRST element at position 4 (index 3)

print(py_list_2d[:3])

print(py_list_2d[:3][0])

print(py_list_2d[3:6][0])

[4, 'D']
4
[[1, 'A'], [2, 'B'], [3, 'C']]
[1, 'A']
[4, 'D']


### 1.4 Indexing & Slicing 2D Arrays

In [5]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

print(np_array_2d[3])      # What is at position 4 (index 3)?

print(np_array_2d[3, 0])    # FIRST element at position 4 (index 3)

print(np_array_2d[:3])

print(np_array_2d[:3, 0])

print(np_array_2d[3:6, 0])

print(np_array_2d[:, 0])



['4' 'D']
4
[['1' 'A']
 ['2' 'B']
 ['3' 'C']]
['1' '2' '3']
['4' '5' '6']
['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


### 1.5 Growing lists

In [6]:
x=[1]*10
print(x)               # I am lazy to type print()
                # Let Jupyter do the hard work.
    
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
print(x)

x=[1]
x+= [2]
x+= [3]
x+= [4]
print(x)

x=[1]
x+= [2, 3, 4]
print(x)

x=[1]
x= [2, 3, 4] + x
print(x)

x=[1]
x.append(2)
x.append(3)
x.append(4)
print(x)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
[1, 2, 3, 4]
[1, 2, 3, 4]
[1, 2, 3, 4]
[2, 3, 4, 1]
[1, 2, 3, 4]


## 2 Some loose ends

### 2.1 Tuples

In [7]:
a=(1, 2, 3)     # Define tuple

print(a[0])    # Access data

# The following will NOT work
#a[0]=-1
#a[0] += [10]

1


### 2.2 Be VERY careful when copying

In [8]:
x=[1, 2, 3]
#y=x           # DON'T do this!
#z=x           # DON'T do this!

x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

- Subsetting - Select a subset
- Indexing - Selecting one element
- Slicing - Selecting a range of elements
- Masking - Only shows elelments that are True/False

## Exercise 2 :  Show me the ‘odd’ letters

In [3]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
my_mask = np_array_2d[:, 0]
print(my_mask)

my_mask2=my_mask.astype(int)

my_mask3=my_mask2%2==1

my_mask4=np_array_2d[my_mask3]

my_mask4[:, 1]

['1' '3' '2' '4' '5' '7' '6' '8' '10' '9']


array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

In [18]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

my_mask=(np_array_2d[:, 0].astype(int))%2==1

my_mask2=np_array_2d[my_mask][:, 1]

print(my_mask2)

['A' 'C' 'E' 'G' 'I']
