<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

In [2]:
import numpy as np

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [6]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(py_real_names[0])

print(py_super_names[0])

print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.

print(py_super_names[-1])   # Reverse indexing

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


### 1.3 Accessing data from a dictionary

In [8]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

print(superhero_info["Natasha Romanoff"])

superhero_info.keys()

superhero_info.values()

Black Widow


dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [9]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

## 2 Lists vs. Arrays

### 2.1 Size

In [14]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

print(len(py_list_2d))

print(len(np_array_2d))

print(np_array_2d.shape)

10
10
(10, 2)


### 2.2 Arrays are fussy about type

In [15]:
py_list = [1, 1.5, 'A']
print(np.array(py_list))

['1' '1.5' 'A']


### 2.3 Adding a number

In [18]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array
        

print(np_array + 10)                 # py_list + 10 Won't work!

[11 12 13 14 15]


### 2.4 Adding another list

In [20]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

print(py_list_1 + py_list_2)

print(np_array_1 + np_array_2)

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]
[11 22 33 44 55]


### 2.5 Multiplying by a Number

In [21]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print(py_list*2)

print(np_array*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


### 2.6 Squaring

In [23]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print(np_array**2)        # print(py_list**2) Won't work!  

[ 1  4  9 16 25]


### 2.7 Asking questions

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

print(py_list == 3)     # Works, but what IS the question?

# print(py_list > 3) Won't work!

print(np_array == 3) 

print(np_array > 3)

False
[False False  True False False]
[False False False  True  True]


### 2.8 Mathematics

In [28]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)

print(sum(py_list))     # sum() is a base Python function

print(max(py_list))     # max() is a base Python function

print(min(py_list))     # min() is a base Python function

# print(py_list.sum()) Won't work!

print(np_array.sum())

print(np_array.mean())

print(np_array.max())

print(np_array.min())

15
5
1
15
3.0
5
1


## Exercise 1 :  Total recall?

In [ ]:



# Your solution here




## Exercise 2 :  Index me

In [ ]:



# Your solution here




## Exercise 3 :  Capitalise Heros

In [ ]:



# Your solution here




## Exercise 4 :  How many ones

In [ ]:



# Your solution here


